### PR TITLE
Travis CI integration + dataprocess function parameterized for wider testing

### PR DESCRIPTION
**Pull request by ajeyamk**
- created appspec.yml file for aws code deployment
- updated travis.yml with deployment configuration
- added scripts/ folder to trigger test cases
- added dataprocess.R for wider testing on dataprocess function
-  added utils folder containing helper functions.

### CODE REVIEW

**Comment by mstaniak** [comment]
@ajeyamk can we move the scripts folder to inst?

**Comment by mstaniak** [comment]
Spaces after comments symbol (#) would look good, please add them

**Comment by mstaniak** [comment]
Is it possible to add the path "/home/rstudio/code/deployment/msstats-dev/tests/utils/" as a parameter to .sh script(s) with a default?

**Comment by mstaniak** [comment]
Why is Navarro dataset treated separately in the constants file?

**Comment by mstaniak** [comment]
@MeenaChoi do you think we need the parameters for converters in dataProcess testing here:
https://github.com/ajeyamk/MSstats-dev/blob/dataprocess-parameterized/tests/dataprocess.R#L84
?

**Comment by ajeyamk** [comment]
> @ajeyamk can we move the scripts folder to inst?

Sure. I can move that folder

**Comment by mstaniak** [comment]
Is it easy enough to reproduce the trick done by skip_on_bioc (https://rdrr.io/cran/testthat/man/skip.html) to make sure only unit tests run on Bioc? I'm worried for example about the xlsx dependency

**Comment by mstaniak** [comment]
I can't see the code that sets column names for xlsx report. Are the columns named more like "number of mismatch XXX" or just "XXX"? (where XXX is for example "Abundance")

**Comment by ajeyamk** [comment]
> Why is Navarro dataset treated separately in the constants file?

I retained those as an example where we can specify the dataset path in a constants path and reading from it instead of hardcoding strings in the tests file

**Comment by ajeyamk** [comment]
> I can't see the code that sets column names for xlsx report. Are the columns named more like "number of mismatch XXX" or just "XXX"? (where XXX is for example "Abundance")

It's here https://github.com/ajeyamk/MSstats-dev/blob/e935a3e18b3f119ccc5bdc2b683650f7650637ad/tests/utils/dataprocess_helper_functions.R#L164 and 
here: https://github.com/ajeyamk/MSstats-dev/blob/e935a3e18b3f119ccc5bdc2b683650f7650637ad/tests/utils/dataprocess_helper_functions.R#L200

**Comment by mstaniak** [comment]
I'd change the name of "infra.R" to something with installation. We don't need MSstatsTMT in MSstats-dev repo.

**Comment by mstaniak** [comment]
btw eventually, this will become a branch of the MSstats repo, so one version will installed from BioC, and the other one from MSstats@develop. How many changes will it require?

**Comment by mstaniak** [comment]
> > I can't see the code that sets column names for xlsx report. Are the columns named more like "number of mismatch XXX" or just "XXX"? (where XXX is for example "Abundance")
> 
> It's here https://github.com/ajeyamk/MSstats-dev/blob/e935a3e18b3f119ccc5bdc2b683650f7650637ad/tests/utils/dataprocess_helper_functions.R#L164 and
> here: https://github.com/ajeyamk/MSstats-dev/blob/e935a3e18b3f119ccc5bdc2b683650f7650637ad/tests/utils/dataprocess_helper_functions.R#L200

Now I get it, thanks. Let's add "mismatched" as a prefix

**Comment by ajeyamk** [comment]
> I'd change the name of "infra.R" to something with installation. We don't need MSstatsTMT in MSstats-dev repo.

I can update the name of the file. TMT library is being used for TMT datasets in the wider testing(E.g: https://github.com/ajeyamk/MSstats-dev/blob/e935a3e18b3f119ccc5bdc2b683650f7650637ad/tests/dataprocess.R#L118) Do I need to remove this logic?

**Comment by ajeyamk** [comment]
> btw eventually, this will become a branch of the MSstats repo, so one version will installed from BioC, and the other one from MSstats@develop. How many changes will it require?

I think we're already doing that in the infrastructure file: https://github.com/ajeyamk/MSstats-dev/blob/dataprocess-parameterized/tests/utils/infra.R

**Comment by mstaniak** [comment]
> > btw eventually, this will become a branch of the MSstats repo, so one version will installed from BioC, and the other one from MSstats@develop. How many changes will it require?
> 
> I think we're already doing that in the infrastructure file: https://github.com/ajeyamk/MSstats-dev/blob/dataprocess-parameterized/tests/utils/infra.R

So it's the only place where there's a dependency on name of the dev version of the package?

**Comment by mstaniak** [comment]
> > I'd change the name of "infra.R" to something with installation. We don't need MSstatsTMT in MSstats-dev repo.
> 
> I can update the name of the file. TMT library is being used for TMT datasets in the wider testing(E.g: https://github.com/ajeyamk/MSstats-dev/blob/e935a3e18b3f119ccc5bdc2b683650f7650637ad/tests/dataprocess.R#L118) Do I need to remove this logic?

Can we add a "is_tmt" parameter to the testing code to run either no TMT datasets or only TMT datasets? And set it to FALSE for this repositor?

**Comment by mstaniak** [comment]
If skipping tests / managing dependencies is hard, no problem. We'll just make releases after removing that part. But if it's possible to make it simpler, let's do it

**Comment by mstaniak** [comment]
One thing I missed: are the results of dataProcess saved on aws?

**Comment by mstaniak** [comment]
(Hopefully) last thing: is it possible to cancel a running checking job?

**Comment by ajeyamk** [comment]
> One thing I missed: are the results of dataProcess saved on aws?

Yes. It'll be stored on AWS S3

**Comment by ajeyamk** [comment]
> (Hopefully) last thing: is it possible to cancel a running checking job?

Not directly at least. We'd have to ssh into the instance and maybe kill the process.

**Comment by mstaniak** [comment]
> > One thing I missed: are the results of dataProcess saved on aws?
> 
> Yes. It'll be stored on AWS S3 
> 

IIRC, there's a file.exists function. So the outputs for stable version can be saved only when they weren't generated earlier. Is this correct?

**Pull request merged**
